# Generated by Django 6.0.2 on 2026-02-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
