# Generated by Django 6.0.2 on 2026-02-26 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegarden', '0002_alter_garden_latitude_alter_garden_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeeHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beehouse_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('beehouse_type', models.CharField(choices=[('block', 'Wood Block'), ('straw', 'Straw Bundle or Container'), ('drilled', 'Drilled Wood'), ('other', 'Other')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=15)),
                ('is_active', models.BooleanField(default=False)),
                ('uninstall_date', models.DateField(blank=True, null=True)),
                ('tube_capacity', models.CharField(choices=[('<100', 'Less than 100 tubes'), ('<200', 'Less than 200 tubes'), ('<300', 'Less than 300 tubes'), ('>300', 'More than 300 tubes')], max_length=10)),
                ('height_above_ground_inches', models.PositiveIntegerField()),
                ('install_date', models.DateField(blank=True, null=True)),
                ('orientation', models.CharField(blank=True, choices=[('North', 'Northward Facing'), ('South', 'Southward Facing'), ('East', 'Eastward Facing'), ('West', 'Westward Facing')], max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beehouses', to='beegarden.garden')),
            ],
            options={
                'unique_together': {('garden', 'beehouse_id')},
            },
        ),
    ]
