# Generated by Django 6.0.2 on 2026-02-28 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegarden', '0007_beehouseevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='beehouseevent',
            name='event_type',
            field=models.CharField(choices=[('emergence', 'Emergence Observed'), ('activated', 'Activated - Added dormant bees to bee house!'), ('deactivated', 'Deactivated - Removed dormant bees from bee house!'), ('tubes_added', 'Tubes Added'), ('cleaned', 'Cleaned'), ('parasite_check', 'Parasite Check'), ('tubes_replaced', 'Tubes Replaced'), ('winterized', 'Winterized'), ('maintenance', 'Maintenance'), ('installed', 'Installed'), ('uninstalled', 'Uninstalled'), ('destroyed', 'Destroyed'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserPinnedGarden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='beegarden.garden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'garden')},
            },
        ),
    ]
