# Generated by Django 6.0.2 on 2026-02-25 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('garden_type', models.CharField(choices=[('community', 'Community Garden'), ('private', 'Private Garden'), ('public', 'Public Area')], default='community', max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('cross_streets', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=255, null=True)),
                ('managed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('num_plots', models.IntegerField(blank=True, null=True)),
                ('size_sqft', models.IntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Only check this box if the garden is open to the public.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this garden (only for private gardens).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
