# Generated by Django 6.0.2 on 2026-02-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegarden', '0003_beehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beehouse',
            name='name',
        ),
        migrations.AlterField(
            model_name='beehouse',
            name='uninstall_date',
            field=models.DateField(blank=True, help_text='Enter uninstall date only if this BeeHouse has been permanently removed or otherwise decommissioned.', null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional. Used to place public gardens on the map. Private gardens can leave this blank.', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional. Private gardens do not need coordinates.', max_digits=15, null=True),
        ),
    ]
