# Generated by Django 6.0.2 on 2026-02-28 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beegarden', '0006_directmessagethread_directmessagethreadparticipant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeeHouseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('installed', 'Installed'), ('cleaned', 'Cleaned'), ('parasite_check', 'Parasite Check'), ('emergence', 'Emergence Observed'), ('tubes_replaced', 'Tubes Replaced'), ('winterized', 'Winterized'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('uninstalled', 'Uninstalled'), ('destroyed', 'Destroyed'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Optional details about the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='beegarden.beehouse')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who recorded the event.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['beehouse', 'created_at'], name='beegarden_b_beehous_2e9d4d_idx'), models.Index(fields=['event_type'], name='beegarden_b_event_t_7ab426_idx')],
            },
        ),
    ]
