# Generated by Django 5.2.12 on 2026-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0013_alter_beehouse_id_alter_beehouseevent_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpinnedgarden",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
