# Generated by Django 5.2.12 on 2026-04-21 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0014_userpinnedgarden_is_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="location_enabled",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="longitude",
        ),
        migrations.AlterField(
            model_name="garden",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Only city-verified gardens may be public."
            ),
        ),
        migrations.AddConstraint(
            model_name="garden",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("owner__isnull", True), ("is_public", False), _connector="OR"
                ),
                name="user_gardens_must_be_private",
            ),
        ),
    ]
