# Generated by Django 5.2.12 on 2026-04-21 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0015_remove_userprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="beehouse",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="beehouse",
            name="clay_nearby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beehouse",
            name="flowers_nearby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beehouse",
            name="garden_description",
            field=models.CharField(
                blank=True,
                help_text="Describe the area where this beehouse is located.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="beehouse",
            name="name",
            field=models.CharField(
                default="beehouse",
                help_text="A short name for this beehouse (e.g., 'Backyard House').",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="beehouse",
            name="water_nearby",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beehouse",
            name="woods_nearby",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="beehouse",
            name="garden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beehouses",
                to="beegarden.garden",
            ),
        ),
        migrations.AlterField(
            model_name="beehouse",
            name="uninstall_date",
            field=models.DateField(
                blank=True,
                help_text="Enter uninstall date only if this BeeHouse has been permanently removed.",
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="beehouse",
            name="beehouse_id",
        ),
    ]
