# Generated by Django 5.2.12 on 2026-04-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "beegarden",
            "0016_alter_beehouse_unique_together_beehouse_clay_nearby_and_more",
        ),
    ]

    operations = []
