# Generated by Django 5.2.12 on 2026-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0017_auto_20260422_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="garden",
            name="source_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
