# Generated by Django 5.2.12 on 2026-04-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0018_garden_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="garden",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="garden",
            name="state",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
