# Generated by Django 5.2.12 on 2026-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0019_garden_city_garden_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garden",
            name="source_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
