# Generated by Django 5.2.12 on 2026-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0020_alter_garden_source_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="garden",
            name="habitat_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
