# Generated by Django 5.2.12 on 2026-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0021_garden_habitat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="beehouse",
            name="beehouse_status",
            field=models.CharField(
                choices=[
                    ("active", "Active bees present"),
                    ("cocoons", "Will be loaded with cocoons"),
                    ("inactive", "Inactive / empty"),
                ],
                default="inactive",
                help_text="Biological status of the beehouse.",
                max_length=20,
            ),
        ),
    ]
