# Generated by Django 5.2.12 on 2026-04-25 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beegarden", "0022_beehouse_beehouse_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="beehouse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 4, 25, 0, 42, 41, 600928, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
